services:
  ez.framework.host:
    image: ez.framework.host
    build:
      context: .
      dockerfile: Ez.Framework.Host/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=9000
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://ez.framework.dashboard:18889
    ports:
        - "9000:9000"
      
  ez.framework.database:
    image: postgres:latest
    container_name: ez.framework.database
    environment:
      - POSTGRES_DB=ez.framework
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  ez.framework.cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
        
  ez.framework.rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      
  ez.framework.dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: dashboard
    ports:
      - 18888:18888
#主从模式+哨兵模式 
#  ez.framework.redis-master:
#    image: redis:latest
#    container_name: redis-master
#    ports:
#      - "6379:6379"
#    volumes:
#      - ./redis-master/data:/data
#    command: ["redis-server", "--appendonly", "yes"]
#
#  ez.framework.redis-slave:
#    image: redis:latest
#    container_name: redis-slave
#    depends_on:
#      - ez.framework.redis-master
#    ports:
#      - "6380:6379"
#    volumes:
#      - ./redis-slave/data:/data
#    command: ["redis-server", "--appendonly", "yes", "--slaveof", "redis-master", "6379"]
#
#  ez.framework.redis-sentinel1:
#    image: redis:latest
#    container_name: redis-sentinel1
#    depends_on:
#      - ez.framework.redis-master
#      - ez.framework.redis-slave
#    ports:
#      - "26379:26379"
#    command:
#      - "redis-sentinel"
#      - "/redis-sentinel/sentinel.conf"
#    volumes:
#      - ./redis-sentinel/sentinel.conf:/redis-sentinel/sentinel.conf
#
#  ez.framework.redis-sentinel2:
#    image: redis:latest
#    container_name: redis-sentinel2
#    depends_on:
#      - ez.framework.redis-master
#      - ez.framework.redis-slave
#    ports:
#      - "26380:26379"
#    command:
#      - "redis-sentinel"
#      - "/redis-sentinel/sentinel.conf"
#    volumes:
#      - ./redis-sentinel/sentinel.conf:/redis-sentinel/sentinel.conf
#
#  ez.framework.redis-sentinel3:
#    image: redis:latest
#    container_name: redis-sentinel3
#    depends_on:
#      - ez.framework.redis-master
#      - ez.framework.redis-slave
#    ports:
#      - "26381:26379"
#    command:
#      - "redis-sentinel"
#      - "/redis-sentinel/sentinel.conf"
#    volumes:
#     - ./redis-sentinel/sentinel.conf:/redis-sentinel/sentinel.conf
