services:
  ez.framework.host:
    image: ez.framework.host
    build:
      context: .
      dockerfile: Ez.Framework.Host/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=9000
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://ez.framework.dashboard:18889
    ports:
        - "9000:9000"
#    volumes:
#      - $HOME/Library/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
#      - $HOME/Library/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - ez.framework

      
  ez.framework.database:
    image: postgres:latest
    container_name: ez.framework.database
    environment:
      - POSTGRES_DB=ez.framework
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - ez.framework
  
  ez.framework.cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    networks:
      - ez.framework
        
  ez.framework.rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - ez.framework
      
  ez.framework.dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: dashboard
    ports:
      - 18888:18888
    networks:
      - ez.framework
networks:
  ez.framework:

